### ISSUE TITLE
subview crash

### ISSUE THREAD

**Issue by soulbuzz** [arconsis/ARTableViewPager#1]
PagerTableList *showList = [[PagerTableList alloc]initWithNumberOfPages:3];
    showList.title = @"Simple Pager";
    showList.titleStrings = [NSArray arrayWithObjects:@"Page 0", @"Page 1",@"Page 2", nil];
    showList.pageControlBackgroundColor = [UIColor lightGrayColor];
    showList.frame = CGRectMake(0, 159, 320, 331);
    [self.view addSubview:showList.view];

When added as a subview it crashed , note that i am trying to add to a much smaller frame.

**Comment by arconsis** [comment]
Initially we didn't have a usage in a smaller frame in mind and build the component for "full screen" ... 
We will try to investigate but that could take some time.
