### ISSUE TITLE
numberOfSectionsInTableView is not optional

### ISSUE THREAD

**Issue by hiaw** [arconsis/ARTableViewPager#2]
Hi,

Just tried it out and was pulling my hair out as it did not work when I implemented all the required methods.

Found out that I had implement 
    - (NSInteger)pageIndex:(NSUInteger)pageIndex numberOfSectionsInTableView:(UITableView *)tableView
in order to get it to work.

**Comment by wfrank2509** [comment]
Thanks for the feedback. We might add that to the documentatiom...
